/* eslint-disable import/no-extraneous-dependencies */
const gulp = require('gulp');
const sass = require('gulp-sass');
const del = require('del');

const paths = {
  static_styles: {
    src: 'src/styles/static/*.scss',
    dest: 'static/styles',
  },
  fontawesome_fonts: {
    src: 'node_modules/@fortawesome/fontawesome-free/webfonts/**',
    dest: 'static/fonts',
  },
  semantic_ui_fonts: {
    src: 'node_modules/semantic-ui-css/themes/**',
    dest: 'static/styles/themes/',
  },
};

/**
 * Cleans the current workingdir and removes all autogenerated files
 */
function clean() {
  return del([paths.static_styles.dest, paths.fontawesome_fonts.dest]);
}

/**
 * Compiles the static scss to css
 */
function styles() {
  return gulp.src(paths.static_styles.src)
    .pipe(sass())
    .pipe(gulp.dest(paths.static_styles.dest));
}

/**
 * Copy webfonts to our local folder (fontawesome)
 */
function fonts() {
  return gulp.src(paths.fontawesome_fonts.src)
    .pipe(gulp.dest(paths.fontawesome_fonts.dest));
}

/**
 * Copy semantic-fonts to our local folder
 */
function semanticFonts() {
  return gulp.src(paths.semantic_ui_fonts.src)
    .pipe(gulp.dest(paths.semantic_ui_fonts.dest));
}

exports.clean = clean;
exports.styles = styles;
exports.fonts = fonts;
exports.semanticFonts = semanticFonts;

exports.default = gulp.series(clean, gulp.parallel(styles, fonts, semanticFonts));
